optimizer: cosangulargrad
scheduler:
  type: CosineAnnealingWarmRestarts
  T_mult: 1
  T_0: 10
  eta_min: 1e-6
model:
  backbone: tf_efficientnet_b4_ns
precision: 32
grad_clip: 0.5
train_params:
  seg_supervision: True
  seg_supervision_weight: 0.1
  mixup: True
  mixup_alpha: 1.0
  img_size: 512
  grad_starvation_fix: True
  grad_rev: True
  epochs: 200
  lr: 5e-4
  num_workers: 4
  batch_size: 24
  csv: /home/jovyan/kaggle/covid/train_folds.csv
