optimizer: adam
batch_size: 16
num_workers: 4
backbone: efficientnet_b4
n_out: 1792
head: v0
img_size: 320
scheduler:
  type: CosineAnnealingWarmRestarts
  T_mult: 1
  T_0: 15
  eta_min: 5e-7
train_params:
  epochs: 200
  lr: 1e-3
  num_workers: 2
