optimizer: adam
batch_size: 16
num_workers: 4
backbone: efficientnet_b4
n_out: 1792
head: v0
img_size: 380
scheduler:
  type: CosineAnnealingWarmRestarts
  T_mult: 1
  T_0: 10
  eta_min: 1e-6
train_params:
  epochs: 200
  lr: 1e-4
  num_workers: 2
