optimizer:
  name: AdamW_GCC2
  lr: 5e-4
  weight_decay: 5e-4
scheduler:
  type: CosineAnnealingWarmRestarts
  T_mult: 2
  T_0: 10
  eta_min: 1e-8
model:
  backbone: timm-efficientnet-b4
  type: Unet
train_params:
  epochs: 200
  batch_size: 32
  num_workers: 4
  train_path: ../input/hubmap/crops1024/train/
  mask_path: ../input/hubmap/crops1024/masks/
precision: 16
clip_grad: 2.0