optimizer: adamw_gcc2
backbone: tf_efficientnet_b4_ns
head: v0
n_out: 1792
img_size: 512
trn_path: input/train_merged
csv_path: input/train_folds_merged.csv
crit: smooth
scheduler:
  type: CosineAnnealingWarmRestarts
  T_mult: 2
  T_0: 10
  eta_min: 1e-6
train_params:
  epochs: 200
  lr: 5e-4
  num_workers: 4
  batch_size: 16
  fold: 0